//HintName: SecondTestEnumeration.g.cs
// <auto-generated>
//     This code was generated by the PMart.Enumeration.Generator source generator.
// </auto-generated>
#nullable enable

using PMart.Enumeration;

namespace Enumeration.Generator.Tests.Source
{
    public partial class SecondTestEnumeration : Enumeration<SecondTestEnumeration>
    {
        public static readonly SecondTestEnumeration CodeA = new(ValueForCodeA);

        private SecondTestEnumeration(string value) : base(value)
        {
        }
    }
}