//HintName: SecondTestEnumeration.g.cs
// <auto-generated>
//     This code was generated by the PMart.Enumeration.Generator source generator.
// </auto-generated>

#nullable enable

namespace Enumeration.Generator.Tests.Source
{
    public partial class SecondTestEnumeration : global::PMart.Enumeration.Enumeration<global::Enumeration.Generator.Tests.Source.SecondTestEnumeration>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.0.0.0")]
        public static readonly global::Enumeration.Generator.Tests.Source.SecondTestEnumeration CodeA = new global::Enumeration.Generator.Tests.Source.SecondTestEnumeration(ValueForCodeA!);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.0.0.0")]
        private SecondTestEnumeration(string value) : base(value)
        {
        }
    }
}