//HintName: TestEnumeration.g.cs
// <auto-generated>
//     This code was generated by the PMart.Enumeration.Generator source generator.
// </auto-generated>

#nullable enable

namespace Enumeration.Generator.Tests.Source.InnerNamespace.MostInnerNamespace
{
    public partial class TestEnumeration : global::PMart.Enumeration.Enumeration<global::Enumeration.Generator.Tests.Source.InnerNamespace.MostInnerNamespace.TestEnumeration>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.1.0.0")]
        public static readonly global::Enumeration.Generator.Tests.Source.InnerNamespace.MostInnerNamespace.TestEnumeration CodeA = new global::Enumeration.Generator.Tests.Source.InnerNamespace.MostInnerNamespace.TestEnumeration(ValueForCodeA!);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.1.0.0")]
        private TestEnumeration(string value) : base(value)
        {
        }
    }
}