//HintName: TestEnumeration.g.cs
// <auto-generated>
//     This code was generated by the PMart.Enumeration.Generator source generator.
// </auto-generated>

#nullable enable

    public partial class TestEnumeration : global::PMart.Enumeration.Enumeration<global::TestEnumeration>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.1.0.0")]
        public static readonly global::TestEnumeration CodeA = new global::TestEnumeration(ValueForCodeA!);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("PMart.Enumeration.Generator", "3.1.0.0")]
        private TestEnumeration(string value) : base(value)
        {
        }
    }