//HintName: TestEnumeration.g.cs
// <auto-generated>
//     This code was generated by the PMart.Enumeration.Generator source generator.
// </auto-generated>
#nullable enable

using PMart.Enumeration;

namespace Enumeration.Generator.Tests.Source
{
    public partial class TestEnumeration : Enumeration<TestEnumeration>
    {
        public static readonly TestEnumeration CodeAa = new(ValueForCodeA);
        public static readonly TestEnumeration CodeBb = new(CodeB);

        private TestEnumeration(string value) : base(value)
        {
        }
    }
}